// Generated by Wrangler on Wed Jun 12 2024 10:48:30 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types`

interface Env {
	MY_DURABLE_OBJECT: DurableObjectNamespace;
	LOGGING_OBJECT: DurableObjectNamespace;
}
